apiVersion: apps/v1
kind: Deployment
metadata:
  name: user
spec:
  replicas: 2
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
    spec:
      containers:
      - image: 751111534101.dkr.ecr.ap-southeast-1.amazonaws.com/user:latest-38cb354f35824dcb0d658c07ec77c2390e8a1fa2
        name: user
        env:
          - name: Application__ConnectionString
            valueFrom:
              secretKeyRef:
                name: organizationsecret-api
                key: databaseconnectionstring
          - name: Application__ReadOnlyConnectionString
            valueFrom:
              secretKeyRef:
                name: organizationsecret-api
                key: ReadOnlyConnectionString
          - name: Application__AmazonSQSConfigurationOptions__accessKey
            valueFrom:
              secretKeyRef:
                name: organizationsecret-api
                key: SQSAccessKey
          - name: Application__AmazonSQSConfigurationOptions__secretKey
            valueFrom:
              secretKeyRef:
                name: organizationsecret-api
                key: SQSSecretKey
          - name: Application__AmazonSQSConfigurationOptions__sqsQueueUrl
            valueFrom:
              secretKeyRef:
                name: organizationsecret-api
                key: SQSQueueUrl
          - name: Application__AmazonS3ConfigurationOptions__accessKey
            valueFrom:
              secretKeyRef:
                name: organizationsecret-api
                key: S3AccessKey
          - name: Application__AmazonS3ConfigurationOptions__secretKey
            valueFrom:
              secretKeyRef:
                name: organizationsecret-api
                key: S3secretKey
        ports:
        - containerPort: 80